HW1 added.
bloowb0und/.NET_HW pull request #1
Opened 2021-12-31 14:46 UTC by bloowb0und

Че-то с гитигнором все сложно получилось :(.

2022-01-04 21:31 UTC, Gribok4E requested changes
Пожалуйста, настрой гитигнор

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +                return false;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +                    curPath = CurrentPath.Substring(0, CurrentPath.Length - (allParts[allParts.Length - 2].Length + 1));
Нужны фигурные скобки

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +                return false;
Нужны фигурные скобки

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +                return false;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
нужен отступ перед return

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +            // File.MoveTo(newPath);
Нужно убирать закоменченный код

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +                File.Delete($"{newPath}\\{fileName}");
Нужны фигурные скобки

2022-01-04 21:31 UTC, Gribok4E commented on MyTerminal/MyTerminal/FileHelper.cs
> +        // ------------------------
Нужно убирать закоменченный код

2022-01-04 22:44 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    }
Это и есть закоменченный CreateFile_ValidString_ReturnsTrue, но у меня вылетает exception при вызове этого метода внутри, потому что у теста нет доступа к тому, чтоб файл создать.

2022-01-04 22:45 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    */
Это метод, который возвращает true, но он немножко у меня не работает, не совсем пойму с чем это связано.

2022-01-04 23:23 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +        // ------------------------
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +                File.Delete($"{newPath}\\{fileName}");
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +            // File.MoveTo(newPath);
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +                return false;
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +                return false;
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +                    curPath = CurrentPath.Substring(0, CurrentPath.Length - (allParts[allParts.Length - 2].Length + 1));
fixed

2022-01-04 23:24 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
fixed

2022-01-04 23:25 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +                return false;
fixed

2022-01-04 23:25 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
fixed

2022-01-04 23:25 UTC, bloowb0und commented on MyTerminal/MyTerminal/FileHelper.cs
> +            return true;
fixed

2022-01-04 23:25 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +        const string input = "";
fixed

2022-01-04 23:26 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +        const string input = "";
fixed

2022-01-04 23:26 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +        const string input = "";
fixed

2022-01-07 00:05 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    */
fixed

2022-01-07 00:05 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    }
fixed

2022-01-07 00:05 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    }
fixed

2022-01-07 00:05 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    }
fixed

2022-01-07 00:06 UTC, bloowb0und commented on MyTerminal/MyTerminal.UnitTests/FileHelperTests.cs
> +    }
fixed

2022-01-07 16:11 UTC, merged